// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// sops.cpp
doubles cpp_markov_propagate(doubles_matrix<> initial, list transitions, integers non_absorb, integers absorb);
extern "C" SEXP _markov_misc_cpp_markov_propagate(SEXP initial, SEXP transitions, SEXP non_absorb, SEXP absorb) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_markov_propagate(cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(initial), cpp11::as_cpp<cpp11::decay_t<list>>(transitions), cpp11::as_cpp<cpp11::decay_t<integers>>(non_absorb), cpp11::as_cpp<cpp11::decay_t<integers>>(absorb)));
  END_CPP11
}
// sops.cpp
doubles cpp_normalize_probability_array(doubles values, int draws, int observations, int states);
extern "C" SEXP _markov_misc_cpp_normalize_probability_array(SEXP values, SEXP draws, SEXP observations, SEXP states) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_normalize_probability_array(cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<int>>(draws), cpp11::as_cpp<cpp11::decay_t<int>>(observations), cpp11::as_cpp<cpp11::decay_t<int>>(states)));
  END_CPP11
}
// sops.cpp
doubles cpp_reduce_sops_draws(doubles values, int draws, int observations, int times, int states, integers groups, int group_count);
extern "C" SEXP _markov_misc_cpp_reduce_sops_draws(SEXP values, SEXP draws, SEXP observations, SEXP times, SEXP states, SEXP groups, SEXP group_count) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_reduce_sops_draws(cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<int>>(draws), cpp11::as_cpp<cpp11::decay_t<int>>(observations), cpp11::as_cpp<cpp11::decay_t<int>>(times), cpp11::as_cpp<cpp11::decay_t<int>>(states), cpp11::as_cpp<cpp11::decay_t<integers>>(groups), cpp11::as_cpp<cpp11::decay_t<int>>(group_count)));
  END_CPP11
}
// sops.cpp
doubles cpp_markov_update_draws(doubles previous, doubles transition, int draws, int observations, int states, integers non_absorb, integers absorb);
extern "C" SEXP _markov_misc_cpp_markov_update_draws(SEXP previous, SEXP transition, SEXP draws, SEXP observations, SEXP states, SEXP non_absorb, SEXP absorb) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_markov_update_draws(cpp11::as_cpp<cpp11::decay_t<doubles>>(previous), cpp11::as_cpp<cpp11::decay_t<doubles>>(transition), cpp11::as_cpp<cpp11::decay_t<int>>(draws), cpp11::as_cpp<cpp11::decay_t<int>>(observations), cpp11::as_cpp<cpp11::decay_t<int>>(states), cpp11::as_cpp<cpp11::decay_t<integers>>(non_absorb), cpp11::as_cpp<cpp11::decay_t<integers>>(absorb)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_markov_misc_cpp_markov_propagate",            (DL_FUNC) &_markov_misc_cpp_markov_propagate,            4},
    {"_markov_misc_cpp_markov_update_draws",         (DL_FUNC) &_markov_misc_cpp_markov_update_draws,         7},
    {"_markov_misc_cpp_normalize_probability_array", (DL_FUNC) &_markov_misc_cpp_normalize_probability_array, 4},
    {"_markov_misc_cpp_reduce_sops_draws",           (DL_FUNC) &_markov_misc_cpp_reduce_sops_draws,           7},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_markov_misc(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
