# Generated by cpp11: do not edit by hand

cpp_markov_propagate <- function(initial, transitions, non_absorb, absorb) {
  .Call(`_markov_misc_cpp_markov_propagate`, initial, transitions, non_absorb, absorb)
}

cpp_normalize_probability_array <- function(values, draws, observations, states) {
  .Call(`_markov_misc_cpp_normalize_probability_array`, values, draws, observations, states)
}

cpp_reduce_sops_draws <- function(values, draws, observations, times, states, groups, group_count) {
  .Call(`_markov_misc_cpp_reduce_sops_draws`, values, draws, observations, times, states, groups, group_count)
}

cpp_markov_update_draws <- function(previous, transition, draws, observations, states, non_absorb, absorb) {
  .Call(`_markov_misc_cpp_markov_update_draws`, previous, transition, draws, observations, states, non_absorb, absorb)
}
