# This tells R CMD check that these variables are used intentionally
# inside dplyr/ggplot2 pipes and are not global variables.
utils::globalVariables(c(
  "id",
  "y",
  "tx",
  "time",
  "yprev",
  "last_not_home",
  "dead",
  "drs",
  "n",
  "count",
  "sop",
  "tx_1",
  "tx_0",
  "true_effect",
  "sd",
  "mean_time",
  "sd_time",
  "Estimate",
  "Pr(>|z|)",
  "Std. Error",
  "analysis",
  "conf_high",
  "conf_low",
  "conf.high",
  "conf.low",
  "rowid",
  "estimate",
  "draw",
  "mean_estimate",
  "p_value",
  "statistic",
  "std_error",
  "term",
  "z value",
  "treatment",
  "t",
  "x",
  "covers_truth",
  "violet_baseline",
  "splits",
  "models",
  "boot_id",
  "draw_id",
  "coefs",
  "value",
  "upper",
  "lower",
  "new_id",
  "block_count",
  "state",
  "probability",
  "median",
  "std.error",
  # Added for format_competing_risks
  "start",
  "status",
  "cum_events",
  "prev_events",
  "next_y",
  # Added for states_to_tte
  "state_change",
  "run_id",
  "raw_start",
  "raw_stop",
  # Added for inferences_bootstrap
  "n_rows",
  # Added for tidy_bootstrap_coefs
  "n_iter"
))
