# This tells R CMD check that these variables are used intentionally
# inside dplyr/ggplot2 pipes and are not global variables.
utils::globalVariables(c(
  "id",
  "y",
  "tx",
  "time",
  "yprev",
  "last_not_home",
  "dead",
  "drs",
  "n",
  "count",
  "sop",
  "tx_1",
  "tx_0",
  "true_effect",
  "sd",
  "mean_time",
  "sd_time",
  "Estimate",
  "Pr(>|z|)",
  "Std. Error",
  "analysis",
  "conf_high",
  "conf_low",
  "estimate",
  "mean_estimate",
  "p_value",
  "statistic",
  "std_error",
  "term",
  "z value",
  "treatment",
  "t",
  "x",
  "covers_truth"
))
