#' Simulate Patient Trajectories Using Brownian Motion Latent Ordinal Model
#'
#' Generates individual patient trajectories based on a latent continuous severity
#' variable that evolves as a Gaussian random walk (Brownian motion) with drift.
#' Observed states are determined by thresholding the latent variable using an
#' ordered logistic or ordered probit model.
#'
#' @param n_patients Integer. Number of patients to simulate (default: 1000).
#' @param follow_up_time Integer. Number of days to simulate per patient (default: 60).
#' @param n_states Integer. Number of ordered states/categories (default: 6).
#' @param mu_drift Numeric. Baseline (constant) drift per day for control group (default: -0.18).
#'   Negative values indicate improvement (movement toward lower severity).
#' @param mu_quad Numeric. Quadratic coefficient for time-varying drift (default: 0).
#'   The drift at time t is: `mu_drift + mu_quad * t + mu_quad2 * t^2`.
#'   Positive values cause the drift to become less negative (slower improvement) over time.
#' @param mu_quad2 Numeric. Second-order quadratic coefficient for drift (default: 0).
#'   Allows for smooth non-linear drift dynamics (e.g., initial increase then decrease).
#'   For example, setting `mu_quad > 0` and `mu_quad2 < 0` creates a drift that
#'   initially increases then decreases.
#' @param mu_treatment_effect Numeric. Additional constant drift for treatment group
#'   (default: 0). Negative values indicate faster improvement with treatment.
#' @param sigma_rw Numeric. Random walk innovation standard deviation per day
#'   (default: 0.12). Lower values create stronger autocorrelation.
#' @param x0_sd Numeric. Standard deviation for baseline latent severity
#'   (default: 1.0).
#' @param thresholds Numeric vector of K-1 cutpoints for the ordered model
#'   (default: c(-3.5, 0, 1, 3, 4.5) for 6 states). Higher values
#'   represent more severe states.
#' @param treatment_prob Numeric. Probability of assignment to treatment group
#'   (default: 0.5).
#' @param allowed_start_state Integer vector or NULL. Defines one or more states allowed at
#'   time 0. If NULL, participants can start in all states (default: 2:5).
#' @param absorbing_state Integer or NULL. State number that represents death or other
#'   absorbing state (default: 6). Once entered, patients remain there.
#'   Set to NULL if no absorbing state is desired.
#' @param drift_change_times Numeric vector of length 2 specifying when drift
#'   begins to decline and when it reaches zero (default: c(25, 50)).
#'   Drift is constant until first time, then linearly declines to 0 by second time.
#'   Note: This piecewise adjustment is applied AFTER the quadratic time effects
#'   (`mu_quad`, `mu_quad2`), allowing both smooth and piecewise dynamics.
#' @param latent_dist Character. The distribution used to link the latent variable
#'   to observed states. Options are "logistic" (default) or "normal".
#'   "logistic" uses the standard logistic CDF (plogis), while "normal" uses
#'   the standard normal CDF (pnorm).
#' @param seed Integer. Random seed for reproducibility (default: NULL).
#'
#' @return A data frame with columns:
#'   - id: patient identifier
#'   - time: time/day (1 to follow_up_time)
#'   - tx: treatment assignment (0 = control, 1 = treatment)
#'   - y: observed ordinal state at time
#'   - x: latent continuous severity (NA after entering absorbing state)
#'
#' @details
#' This function implements a latent variable model where:
#' 1. Each patient has an unobserved continuous "severity" X(t) that evolves
#'    as a Gaussian random walk: X(t) = X(t - 1) + mu(t) + epsilon,
#'    where epsilon ~ N(0, sigma^2).
#' 2. The drift mu(t) depends on treatment assignment and time:
#'    mu(t) = (mu_drift + mu_quad * t + mu_quad2 * t^2 +
#'    tx * mu_treatment_effect) * piecewise_factor
#'    where piecewise_factor applies the drift_change_times logic (1 before first time,
#'    linearly declining to 0 between first and second time, 0 after).
#' 3. Observed states Y(t) are generated by thresholding X(t).
#'    If `latent_dist = "logistic"`, P(Y <= k) = logit^-1(c_k - X).
#'    If `latent_dist = "normal"`, P(Y <= k) = Phi(c_k - X).
#' 4. Once a patient enters the absorbing state (death), they remain there.
#'
#' @examples
#' \dontrun{
#' # Standard Logistic model
#' traj_logit <- sim_trajectories_brownian(
#'   n_patients = 1000,
#'   latent_dist = "logistic"
#' )
#'
#' # Probit model which approximates viral respiratory trajectories okay-ishly
#' # Because standard normal is narrower than logistic, use closer thresholds,
#' # smaller drift, and lower variance.
#' traj_norm <- sim_trajectories_brownian(n_patients = 1000,
#'   latent_dist = "normal",
#'   thresholds = c(-3, -1.0, 0.5, 2, 3),
#'   mu_drift = -0.12,
#'   drift_change_times = c(40, 50),
#'   sigma_rw = 0.02)
#'
#' # Smooth non-linear drift: initial worsening that reverses to improvement
#' # The quadratic terms create a U-shaped or inverted-U drift curve
#' traj_nonlinear <- sim_trajectories_brownian(
#'   n_patients = 1000,
#'   mu_drift = 0.05,       # slight initial worsening
#'   mu_quad = -0.002,      # drift becomes more negative over time
#'   mu_quad2 = 0,          # no second-order curvature
#'   drift_change_times = c(60, 61)  # disable piecewise decline
#' )
#' }
#'
#' @importFrom stats rnorm plogis pnorm
#'
#' @export
sim_trajectories_brownian <- function(
  n_patients = 1000,
  follow_up_time = 60,
  n_states = 6,
  mu_drift = -0.18,
  mu_quad = 0,
  mu_quad2 = 0,
  mu_treatment_effect = 0,
  sigma_rw = 0.12,
  x0_sd = 1.0,
  thresholds = c(-3.5, 0, 1, 3, 4.5),
  treatment_prob = 0.5,
  allowed_start_state = 2:5,
  absorbing_state = 6,
  drift_change_times = c(25, 50),
  latent_dist = c("logistic", "normal"),
  seed = NULL
) {
  # Input validation
  if (n_patients < 1 || !is.numeric(n_patients)) {
    stop("n_patients must be a positive integer")
  }

  if (follow_up_time < 1 || !is.numeric(follow_up_time)) {
    stop("follow_up_time must be a positive integer")
  }

  if (n_states < 2 || !is.numeric(n_states)) {
    stop("n_states must be at least 2")
  }

  if (length(thresholds) != (n_states - 1)) {
    stop(
      "thresholds must have length n_states - 1 (",
      n_states - 1,
      "), but has length ",
      length(thresholds)
    )
  }

  if (!is.numeric(thresholds) || !all(diff(thresholds) > 0)) {
    stop("thresholds must be a strictly increasing numeric vector")
  }

  if (treatment_prob < 0 || treatment_prob > 1) {
    stop("treatment_prob must be between 0 and 1")
  }

  if (!is.null(allowed_start_state)) {
    if (!is.integer(allowed_start_state)) {
      stop("allowed_start_state must be NULL or an integer")
    }
    if (!all(allowed_start_state %in% 1:n_states)) {
      stop("All allowed_start_state must be between 1 and n_states")
    }
  }

  if (!is.null(absorbing_state)) {
    if (absorbing_state < 1 || absorbing_state > n_states) {
      stop("absorbing_state must be between 1 and n_states")
    }
  }

  if (
    !is.null(drift_change_times) &
      (length(drift_change_times) != 2 ||
        drift_change_times[1] >= drift_change_times[2])
  ) {
    stop(
      "drift_change_times must be a vector of length 2 with increasing values"
    )
  }

  # Validate and select distribution
  latent_dist <- match.arg(latent_dist)

  # Select the appropriate Cumulative Distribution Function
  # Assigning this before the loop improves performance
  cdf_fun <- if (latent_dist == "logistic") {
    stats::plogis
  } else {
    stats::pnorm
  }

  # Set seed if provided
  if (!is.null(seed)) {
    set.seed(seed)
  }

  calc_piecewise_factor <- function(day) {
    if (is.null(drift_change_times) || day <= drift_change_times[1]) {
      return(1)
    }

    if (day <= drift_change_times[2]) {
      return(
        (drift_change_times[2] - day) /
          (drift_change_times[2] - drift_change_times[1])
      )
    }

    0
  }

  calc_shared_drift <- function(day, tx) {
    mu_base <- mu_drift + mu_quad * day + mu_quad2 * day^2
    (mu_base + tx * mu_treatment_effect) * calc_piecewise_factor(day)
  }

  # Randomly assign treatment
  treatment <- sample(
    c(0, 1),
    n_patients,
    replace = TRUE,
    prob = c(1 - treatment_prob, treatment_prob)
  )

  # Initialize matrices for latent X and observed Y
  # Need follow_up_time + 1 columns to include time 0
  X <- matrix(NA_real_, n_patients, follow_up_time + 1)
  Y <- matrix(NA_integer_, n_patients, follow_up_time + 1)

  X[, 1L] <- stats::rnorm(n_patients, 0, x0_sd)
  cumulative <- cdf_fun(outer(-X[, 1L], thresholds, "+"))
  probabilities <- cbind(cumulative, 1) - cbind(0, cumulative)
  if (!is.null(allowed_start_state)) {
    probabilities[, -allowed_start_state] <- 0
  }
  Y[, 1L] <- sample_categorical_rows(probabilities)

  for (column in 2:(follow_up_time + 1L)) {
    day <- column - 1L
    active <- if (is.null(absorbing_state)) {
      rep(TRUE, n_patients)
    } else {
      Y[, column - 1L] != absorbing_state
    }
    Y[, column] <- Y[, column - 1L]
    X[, column] <- NA_real_
    if (!any(active)) {
      next
    }
    drift <- calc_shared_drift(day, treatment[active])
    X[active, column] <- stats::rnorm(
      sum(active),
      mean = X[active, column - 1L] + drift,
      sd = sigma_rw
    )
    cumulative <- cdf_fun(outer(-X[active, column], thresholds, "+"))
    probabilities <- cbind(cumulative, 1) - cbind(0, cumulative)
    Y[active, column] <- sample_categorical_rows(probabilities)
  }

  result <- data.frame(
    id = rep(seq_len(n_patients), each = follow_up_time),
    tx = rep(treatment, each = follow_up_time),
    time = rep(seq_len(follow_up_time), times = n_patients),
    # Keep the historical public type produced by the former data-frame path.
    y = as.numeric(as.vector(t(Y[, -1L, drop = FALSE]))),
    yprev = as.numeric(as.vector(t(Y[, -(follow_up_time + 1L), drop = FALSE]))),
    x = as.vector(t(X[, -1L, drop = FALSE])),
    check.names = FALSE
  )
  rownames(result) <- NULL

  return(result)
}
